ALTER TABLE photo_notes ADD COLUMN IF NOT EXISTS image_thumbnail MEDIUMTEXT NULL;
ALTER TABLE photo_notes ADD COLUMN IF NOT EXISTS image_key VARCHAR(512) NULL;
ALTER TABLE photo_notes ADD COLUMN IF NOT EXISTS image_thumbnail_key VARCHAR(512) NULL;
